# Generated by Django 4.1.3 on 2022-11-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_title", models.CharField(max_length=200)),
                ("draw_payload", models.TextField(max_length=2000)),
            ],
        ),
    ]
