# Generated by Django 4.1.3 on 2022-11-11 03:11

from django.db import migrations, models
import draws.validators


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0002_alter_draw_draw_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draw",
            name="draw_payload",
            field=models.TextField(validators=[draws.validators.validate_draw_payload]),
        ),
    ]
